server:
  port: 9091

spring:
  application:
    name: company-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/e-invoice"
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/companies.db
    password: psql
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true

keycloak:
  location_path: "/admin/realms/e-invoice/users/"
  server_url: "http://localhost:8080/"
  master_realm: master
  realm: e-invoice
  client_id: admin-cli
  username: admin
  password: 123